### ISSUE TITLE
(ASK) Nest ^9

### ISSUE THREAD

**Issue by conioX** [adrianbrs/nest-oidc-provider#16]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

it possible to use this library with latest nest? 

### Describe the solution you'd like

upgrade to nest ^9

### Teachability, documentation, adoption, migration strategy

-

### What is the motivation / use case for changing the behavior?

-

**Comment by adrianbrs** [comment]
Hi @conioX, sorry for the late reply.
Yes, it is possible to use this library with Nest version `^9`. I've updated the example project with Nest version `^9.2.0` and it seems to work fine.
