### ISSUE TITLE
Node v18 not allowed

### ISSUE THREAD

**Issue by davidzwa** [adrianbrs/nest-oidc-provider#19]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When installing the package I get the error "The engine "node" is incompatible with this module. Expected version "^12.19.0 || ^14.15.0 || ^16.13.0". Got "18.12.1""

### Steps to reproduce

1. `npm ci`
2. Get error

### Expected behavior

Node v18 should work fine as oidc-provider supports it: https://github.com/panva/node-oidc-provider/blob/efd5344216017860fb01f015e3ae3a29273f1f89/package.json#L106

### NestJS version

9.2.0

### Packages versions

```json

```

### Node.js version

18.12.1

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [X] Linux

**Comment by adrianbrs** [comment]
Released `v1.1.1`.
Thanks!
