### ISSUE TITLE
Require error with openid-provider 8

### ISSUE THREAD

**Issue by bvanleeuwen1995** [adrianbrs/nest-oidc-provider#22]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Installing with node-oids-provider 8 returns the following error: `Error [ERR_REQUIRE_ESM]: require() of ES Module sso/node_modules/oidc-provider/lib/index.js from sso/node_modules/nest-oidc-provider/dist/oidc.service.js not supported.
Instead change the require of index.js in sso/node_modules/nest-oidc-provider/dist/oidc.service.js to a dynamic import() which is available in all CommonJS modules.`

### Expected behavior

Application is able to start without errors

### oidc-provider version

8.1.1

### nest-oidc-provider version

1.1.1

### NestJS version

9.4.0

### Packages versions

```json

```

### Node.js version

18.15.0

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by bvanleeuwen1995** [comment]
If needed I can create an empty project to reproduce this error

**Comment by Soulusions** [comment]
I'm experiencing the exact same issue on Linux, even with the example project

**Comment by undervane** [comment]
@bvanleeuwen1995 @Soulusions I've been also experiencing this very same issue and unfortunately there's nothing we could ask library maintainer to change here, since this is something strictly related to the base oidc-provider library. Starting with [v8](https://github.com/panva/node-oidc-provider/releases/tag/v8.0.0), the base library this NestJs wrapper is using has turned into an ESM-only module so if you (or the complier you use, like Webpack) is traspiling by using CommonJS then you may have the error described here

**Comment by adrianbrs** [comment]
@undervane thank you for the explanation!
NestJS doesn't support ESM-only packages https://github.com/nestjs/nest/issues/7021. There's also a WIP PR to support multiple build formats https://github.com/nestjs/nest/pull/8736. Unfortunately there's nothing I can do in the scope of this library to solve this problem until they add support for ESM-only packages :(

**Comment by adrianbrs** [comment]
Hello everyone!

Version [2.0.0](https://github.com/adrianbrs/nest-oidc-provider/releases/tag/2.0.0) is now available 🚀, offering an alternative that supports `oidc-provider@8` through dynamic imports. Additionally, there's a note on using Node.js >= 20.17.x, which allows `require` in ESM modules and can be helpful if you're encountering this issue with other packages.

I hope this update proves useful! If you have any questions, feel free to reach out, start a discussion, or open an issue.
