### ISSUE TITLE
JWT Token is not invalidated on logout from browser

### ISSUE THREAD

**Issue by raksrivastava** [adrianbrs/nest-oidc-provider#25]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

JWT Token is not invalidated on logout from browser

### Expected behavior

I have logout from browser, but still can get data from /me API

### oidc-provider version

7.14.3

### nest-oidc-provider version

1.1.1

### NestJS version

7.6.0

### Packages versions

```json

```

### Node.js version

18

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [X] Linux

**Comment by adrianbrs** [comment]
Hello @raksrivastava! The JWT token is stateless and has an expiration date, meaning it remains valid until that date, even after you log out.

BTW, this library serves as an integration between `oidc-provider` and Nest. If you need further assistance, I recommend visiting the [oidc-provider](https://github.com/panva/node-oidc-provider) project and perhaps starting a discussion there.
