### ISSUE TITLE
client_id is mandatory property

### ISSUE THREAD

**Issue by sshhawwnn** [adrianbrs/nest-oidc-provider#8]
I am facing this weird issue that doesn't explains much other than the following message when accessing via web /oidc/auth?client_id=xxx or through postman grant_type=client_credentials

```
error: invalid_client_metadata
error_description: client_id is mandatory property
```

**Comment by adrianbrs** [comment]
Hi @sshhawwnn!
This error means that the client you are using is invalid, it's missing the `client_id` required property.
I have tested it chaning the example project of this repo to return a dynamic client from the adapter, with the `client_id` property missing, and the error you described was thrown:

![image](https://user-images.githubusercontent.com/20914057/183230724-acf32596-be83-4828-80c4-db6e531747eb.png)

Anyway if it's not the case, this error seems to be related to the [`oidc-provider`](https://github.com/panva/node-oidc-provider) package, and not [`nest-oidc-provider`](https://github.com/adrianbrs/nest-oidc-provider) (which is only a module of the `oidc-provider` package for the Nest framework), so I'm going to close this issue for now. But feel free to start a new discussion if you need some help :)

(sorry for the delay in responding)
